version: '3'
services:
  client:
    image: engtomno/tomno-clinton-app:latest
    stdin_open: true
    tty: true 
    ports:
      - "3000:3000"
  backend:
    depends_on:
      - mongo
    image: engtomno/tomno-clinton-app-backend:latest
    stdin_open: true
    tty: true 
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb://mongo/
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
    ports:
      - '27017:27017'


volumes:
  db:
