apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  selector:
    matchLabels:
      run: mongo-app
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo
        ports:
        - containerPort: 27017